export interface Product {
    id: string;
    name: string;
    category: 'electronics' | 'fashion' | 'home' | 'health' | 'mobile' | 'computer' | 'accessories' | 'other';
    price: number;            // Offered Price
    previousPrice?: number;   // Previous Price
    returnRate: number;       // Auto-sell Return Rate
    duration: number;         // Duration in days
    stock: number;
    description: string;
    image?: string;           // icon/image
    active: boolean;
    colors?: string[];        // Color options
    createdAt?: string;
    minUnits?: number;
    hasOffer?: boolean;
    offerText?: string;
    offerColor?: string;
}

export const defaultProducts: Product[] = [
    {
        "id": "1",
        "name": "LED Makeup Mirror",
        "category": "health",
        "price": 650,
        "previousPrice": 780,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality LED Makeup Mirror (BTY-001)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "2",
        "name": "Makeup Organizer",
        "category": "health",
        "price": 450,
        "previousPrice": 540,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Makeup Organizer (BTY-002)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "3",
        "name": "Cosmetic Bag",
        "category": "health",
        "price": 250,
        "previousPrice": 300,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Cosmetic Bag (BTY-003)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "4",
        "name": "Facial Ice Roller",
        "category": "health",
        "price": 350,
        "previousPrice": 420,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Facial Ice Roller (BTY-004)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "5",
        "name": "Face Massager (Mini)",
        "category": "health",
        "price": 550,
        "previousPrice": 660,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Face Massager (Mini) (BTY-005)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "6",
        "name": "Blackhead Remover",
        "category": "health",
        "price": 300,
        "previousPrice": 360,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Blackhead Remover (BTY-006)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "7",
        "name": "Nail Kit",
        "category": "health",
        "price": 350,
        "previousPrice": 420,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Nail Kit (BTY-007)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "8",
        "name": "Makeup Brush Set",
        "category": "health",
        "price": 400,
        "previousPrice": 480,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Makeup Brush Set (BTY-008)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "9",
        "name": "Perfume Atomizer (Travel)",
        "category": "health",
        "price": 200,
        "previousPrice": 240,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Perfume Atomizer (Travel) (BTY-009)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "10",
        "name": "Trimmer",
        "category": "health",
        "price": 550,
        "previousPrice": 660,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Trimmer (BTY-010)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "11",
        "name": "Foot File",
        "category": "health",
        "price": 150,
        "previousPrice": 180,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Foot File (BTY-011)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "12",
        "name": "Face Cleansing Brush",
        "category": "health",
        "price": 350,
        "previousPrice": 420,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Face Cleansing Brush (BTY-012)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "13",
        "name": "Beauty Storage Box",
        "category": "health",
        "price": 450,
        "previousPrice": 540,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Beauty Storage Box (BTY-013)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "14",
        "name": "Hair Straightener",
        "category": "health",
        "price": 1300,
        "previousPrice": 1560,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Hair Straightener (BTY-014)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "15",
        "name": "Electric Toothbrush",
        "category": "health",
        "price": 1100,
        "previousPrice": 1320,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Electric Toothbrush (BTY-015)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "16",
        "name": "Drawer Organizer",
        "category": "other",
        "price": 350,
        "previousPrice": 420,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Drawer Organizer (HOM-001)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "17",
        "name": "Wardrobe Organizer",
        "category": "other",
        "price": 550,
        "previousPrice": 660,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Wardrobe Organizer (HOM-002)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "18",
        "name": "Foldable Storage Box",
        "category": "other",
        "price": 450,
        "previousPrice": 540,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Foldable Storage Box (HOM-003)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "19",
        "name": "Under Bed Storage Bag",
        "category": "other",
        "price": 500,
        "previousPrice": 600,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Under Bed Storage Bag (HOM-004)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "20",
        "name": "Shoe Rack (Foldable)",
        "category": "other",
        "price": 750,
        "previousPrice": 900,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Shoe Rack (Foldable) (HOM-005)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "21",
        "name": "Hanging Shelf",
        "category": "other",
        "price": 400,
        "previousPrice": 480,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Hanging Shelf (HOM-006)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "22",
        "name": "Closet Hanger (Set)",
        "category": "other",
        "price": 300,
        "previousPrice": 360,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Closet Hanger (Set) (HOM-007)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "23",
        "name": "Cable Organizer Box",
        "category": "other",
        "price": 350,
        "previousPrice": 420,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Cable Organizer Box (HOM-008)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "24",
        "name": "Sticky Wall Hooks (Set)",
        "category": "other",
        "price": 150,
        "previousPrice": 180,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Sticky Wall Hooks (Set) (HOM-009)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "25",
        "name": "Bathroom Shelf",
        "category": "other",
        "price": 450,
        "previousPrice": 540,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Bathroom Shelf (HOM-010)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "26",
        "name": "Toothbrush Holder",
        "category": "other",
        "price": 200,
        "previousPrice": 240,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Toothbrush Holder (HOM-011)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "27",
        "name": "Tissue Box Holder",
        "category": "other",
        "price": 250,
        "previousPrice": 300,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Tissue Box Holder (HOM-012)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "28",
        "name": "Laundry Basket",
        "category": "other",
        "price": 500,
        "previousPrice": 600,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Laundry Basket (HOM-013)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "29",
        "name": "Jewelry Organizer",
        "category": "other",
        "price": 400,
        "previousPrice": 480,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Jewelry Organizer (HOM-014)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "30",
        "name": "Cosmetic Storage Box",
        "category": "other",
        "price": 450,
        "previousPrice": 540,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Cosmetic Storage Box (HOM-015)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "31",
        "name": "Desktop Organizer",
        "category": "other",
        "price": 350,
        "previousPrice": 420,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Desktop Organizer (HOM-016)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "32",
        "name": "Book Stand",
        "category": "other",
        "price": 300,
        "previousPrice": 360,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Book Stand (HOM-017)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "33",
        "name": "Laundry Clips (Set)",
        "category": "other",
        "price": 150,
        "previousPrice": 180,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Laundry Clips (Set) (HOM-018)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "34",
        "name": "Storage Basket",
        "category": "other",
        "price": 400,
        "previousPrice": 480,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Storage Basket (HOM-019)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "35",
        "name": "Fridge Organizer (Set)",
        "category": "other",
        "price": 450,
        "previousPrice": 540,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Fridge Organizer (Set) (HOM-020)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "36",
        "name": "Phone Case",
        "category": "other",
        "price": 250,
        "previousPrice": 300,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Phone Case (MOB-001)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "37",
        "name": "Tempered Glass",
        "category": "other",
        "price": 150,
        "previousPrice": 180,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Tempered Glass (MOB-002)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "38",
        "name": "Charging Cable",
        "category": "other",
        "price": 200,
        "previousPrice": 240,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Charging Cable (MOB-003)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "39",
        "name": "Car Charger",
        "category": "other",
        "price": 300,
        "previousPrice": 360,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Car Charger (MOB-004)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "40",
        "name": "Phone Holder",
        "category": "other",
        "price": 250,
        "previousPrice": 300,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Phone Holder (MOB-005)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "41",
        "name": "Tablet Holder",
        "category": "other",
        "price": 350,
        "previousPrice": 420,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Tablet Holder (MOB-006)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "42",
        "name": "Selfie Stick",
        "category": "other",
        "price": 300,
        "previousPrice": 360,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Selfie Stick (MOB-007)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "43",
        "name": "Ring Light (Mini)",
        "category": "other",
        "price": 450,
        "previousPrice": 540,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Ring Light (Mini) (MOB-008)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "44",
        "name": "Pop Socket",
        "category": "other",
        "price": 150,
        "previousPrice": 180,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Pop Socket (MOB-009)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "45",
        "name": "Cable Protector",
        "category": "other",
        "price": 100,
        "previousPrice": 120,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Cable Protector (MOB-010)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "46",
        "name": "SD Card Reader",
        "category": "other",
        "price": 300,
        "previousPrice": 360,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality SD Card Reader (MOB-011)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "47",
        "name": "OTG Adapter",
        "category": "other",
        "price": 200,
        "previousPrice": 240,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality OTG Adapter (MOB-012)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "48",
        "name": "USB Hub",
        "category": "other",
        "price": 400,
        "previousPrice": 480,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality USB Hub (MOB-013)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "49",
        "name": "Mouse",
        "category": "other",
        "price": 350,
        "previousPrice": 420,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Mouse (MOB-014)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "50",
        "name": "Mouse Pad",
        "category": "other",
        "price": 150,
        "previousPrice": 180,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Mouse Pad (MOB-015)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "51",
        "name": "Keyboard Cover",
        "category": "other",
        "price": 200,
        "previousPrice": 240,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Keyboard Cover (MOB-016)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "52",
        "name": "Cleaning Kit (Electronics)",
        "category": "other",
        "price": 250,
        "previousPrice": 300,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Cleaning Kit (Electronics) (MOB-017)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "53",
        "name": "Laptop Stand",
        "category": "other",
        "price": 1200,
        "previousPrice": 1440,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Laptop Stand (MOB-018)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "54",
        "name": "Cooling Pad",
        "category": "other",
        "price": 1100,
        "previousPrice": 1320,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Cooling Pad (MOB-019)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "55",
        "name": "Couple Mug (Set)",
        "category": "home",
        "price": 400,
        "previousPrice": 480,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Couple Mug (Set) (CPL-001)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "56",
        "name": "Couple Keychain (Set)",
        "category": "home",
        "price": 250,
        "previousPrice": 300,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Couple Keychain (Set) (CPL-002)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "57",
        "name": "Couple Bracelet",
        "category": "home",
        "price": 350,
        "previousPrice": 420,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Couple Bracelet (CPL-003)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "58",
        "name": "Matching Water Bottle",
        "category": "home",
        "price": 450,
        "previousPrice": 540,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Matching Water Bottle (CPL-004)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "59",
        "name": "Couple Pillow Cover",
        "category": "home",
        "price": 500,
        "previousPrice": 600,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Couple Pillow Cover (CPL-005)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "60",
        "name": "Couple Frame",
        "category": "home",
        "price": 400,
        "previousPrice": 480,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Couple Frame (CPL-006)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "61",
        "name": "Scratch Date Cards",
        "category": "home",
        "price": 350,
        "previousPrice": 420,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Scratch Date Cards (CPL-007)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "62",
        "name": "Love Jar",
        "category": "home",
        "price": 400,
        "previousPrice": 480,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Love Jar (CPL-008)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "63",
        "name": "Anniversary Box",
        "category": "home",
        "price": 650,
        "previousPrice": 780,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Anniversary Box (CPL-009)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "64",
        "name": "Love Lamp",
        "category": "home",
        "price": 1300,
        "previousPrice": 1560,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Love Lamp (CPL-010)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "65",
        "name": "Vegetable Chopper (Manual, Multi-blade)",
        "category": "other",
        "price": 350,
        "previousPrice": 420,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Vegetable Chopper (Manual, Multi-blade) (KIT-001)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "66",
        "name": "Garlic Press",
        "category": "other",
        "price": 150,
        "previousPrice": 180,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Garlic Press (KIT-002)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "67",
        "name": "Oil Spray Bottle",
        "category": "other",
        "price": 200,
        "previousPrice": 240,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Oil Spray Bottle (KIT-003)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "68",
        "name": "Egg Boiler (Electric)",
        "category": "other",
        "price": 650,
        "previousPrice": 780,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Egg Boiler (Electric) (KIT-004)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "69",
        "name": "Food Storage Container (Set)",
        "category": "other",
        "price": 450,
        "previousPrice": 540,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Food Storage Container (Set) (KIT-005)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "70",
        "name": "Lunch Box (Insulated)",
        "category": "other",
        "price": 400,
        "previousPrice": 480,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Lunch Box (Insulated) (KIT-006)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "71",
        "name": "Vacuum Food Bags (Set)",
        "category": "other",
        "price": 300,
        "previousPrice": 360,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Vacuum Food Bags (Set) (KIT-007)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "72",
        "name": "Sink Organizer",
        "category": "other",
        "price": 350,
        "previousPrice": 420,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Sink Organizer (KIT-008)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "73",
        "name": "Dish Drying Rack",
        "category": "other",
        "price": 550,
        "previousPrice": 660,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Dish Drying Rack (KIT-009)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "74",
        "name": "Silicone Spoon Rest",
        "category": "other",
        "price": 150,
        "previousPrice": 180,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Silicone Spoon Rest (KIT-010)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "75",
        "name": "Measuring Cups (Set)",
        "category": "other",
        "price": 200,
        "previousPrice": 240,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Measuring Cups (Set) (KIT-011)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "76",
        "name": "Measuring Spoons (Set)",
        "category": "other",
        "price": 150,
        "previousPrice": 180,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Measuring Spoons (Set) (KIT-012)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "77",
        "name": "Spice Rack",
        "category": "other",
        "price": 400,
        "previousPrice": 480,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Spice Rack (KIT-013)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "78",
        "name": "Knife Sharpener",
        "category": "other",
        "price": 250,
        "previousPrice": 300,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Knife Sharpener (KIT-014)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "79",
        "name": "Vegetable Peeler",
        "category": "other",
        "price": 100,
        "previousPrice": 120,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Vegetable Peeler (KIT-015)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "80",
        "name": "Ice Cube Tray (Silicone)",
        "category": "other",
        "price": 150,
        "previousPrice": 180,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Ice Cube Tray (Silicone) (KIT-016)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "81",
        "name": "Silicone Baking Tools (Set)",
        "category": "other",
        "price": 450,
        "previousPrice": 540,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Silicone Baking Tools (Set) (KIT-017)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "82",
        "name": "Portable Blender (USB)",
        "category": "other",
        "price": 750,
        "previousPrice": 900,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Portable Blender (USB) (KIT-018)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "83",
        "name": "Electric Milk Frother",
        "category": "other",
        "price": 400,
        "previousPrice": 480,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Electric Milk Frother (KIT-019)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "84",
        "name": "Building Blocks",
        "category": "home",
        "price": 450,
        "previousPrice": 540,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Building Blocks (KID-001)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "85",
        "name": "Drawing Board (Magic)",
        "category": "home",
        "price": 350,
        "previousPrice": 420,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Drawing Board (Magic) (KID-002)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "86",
        "name": "LCD Writing Tablet",
        "category": "home",
        "price": 400,
        "previousPrice": 480,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality LCD Writing Tablet (KID-003)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "87",
        "name": "Coloring Set",
        "category": "home",
        "price": 250,
        "previousPrice": 300,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Coloring Set (KID-004)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "88",
        "name": "Puzzle Game",
        "category": "home",
        "price": 300,
        "previousPrice": 360,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Puzzle Game (KID-005)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "89",
        "name": "Rubik's Cube",
        "category": "home",
        "price": 200,
        "previousPrice": 240,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Rubik's Cube (KID-006)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "90",
        "name": "Bubble Gun",
        "category": "home",
        "price": 350,
        "previousPrice": 420,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Bubble Gun (KID-007)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "91",
        "name": "Cartoon Water Bottle",
        "category": "home",
        "price": 300,
        "previousPrice": 360,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Cartoon Water Bottle (KID-008)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "92",
        "name": "School Lunch Box",
        "category": "home",
        "price": 400,
        "previousPrice": 480,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality School Lunch Box (KID-009)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "93",
        "name": "Cartoon Night Lamp",
        "category": "home",
        "price": 450,
        "previousPrice": 540,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Cartoon Night Lamp (KID-010)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "94",
        "name": "Piggy Bank",
        "category": "home",
        "price": 300,
        "previousPrice": 360,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Piggy Bank (KID-011)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "95",
        "name": "Educational Flash Cards",
        "category": "home",
        "price": 250,
        "previousPrice": 300,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Educational Flash Cards (KID-012)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "96",
        "name": "Fidget Toys",
        "category": "home",
        "price": 200,
        "previousPrice": 240,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Fidget Toys (KID-013)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "97",
        "name": "Pop It Toys",
        "category": "home",
        "price": 150,
        "previousPrice": 180,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Pop It Toys (KID-014)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "98",
        "name": "Soft Plush Toys",
        "category": "home",
        "price": 450,
        "previousPrice": 540,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Soft Plush Toys (KID-015)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "99",
        "name": "STEM Learning Toys",
        "category": "home",
        "price": 1200,
        "previousPrice": 1440,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality STEM Learning Toys (KID-016)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "100",
        "name": "Gift Boxes (Set)",
        "category": "mobile",
        "price": 300,
        "previousPrice": 360,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Gift Boxes (Set) (GFT-001)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "101",
        "name": "Artificial Rose Box",
        "category": "mobile",
        "price": 550,
        "previousPrice": 660,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Artificial Rose Box (GFT-002)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "102",
        "name": "Teddy Bear (Medium)",
        "category": "mobile",
        "price": 450,
        "previousPrice": 540,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Teddy Bear (Medium) (GFT-003)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "103",
        "name": "Moon Lamp",
        "category": "mobile",
        "price": 650,
        "previousPrice": 780,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Moon Lamp (GFT-004)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "104",
        "name": "Mini Photo Frame",
        "category": "mobile",
        "price": 250,
        "previousPrice": 300,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Mini Photo Frame (GFT-005)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "105",
        "name": "Greeting Cards",
        "category": "mobile",
        "price": 100,
        "previousPrice": 120,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Greeting Cards (GFT-006)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "106",
        "name": "Chocolate Box",
        "category": "mobile",
        "price": 400,
        "previousPrice": 480,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Chocolate Box (GFT-007)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "107",
        "name": "Mug Gift Set",
        "category": "mobile",
        "price": 350,
        "previousPrice": 420,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Mug Gift Set (GFT-008)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "108",
        "name": "Keychain Gift Set",
        "category": "mobile",
        "price": 200,
        "previousPrice": 240,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Keychain Gift Set (GFT-009)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "109",
        "name": "Name Keychain",
        "category": "mobile",
        "price": 150,
        "previousPrice": 180,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Name Keychain (GFT-010)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "110",
        "name": "Mini Snow Globe",
        "category": "mobile",
        "price": 350,
        "previousPrice": 420,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Mini Snow Globe (GFT-011)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "111",
        "name": "Decorative Candle",
        "category": "mobile",
        "price": 250,
        "previousPrice": 300,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Decorative Candle (GFT-012)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "112",
        "name": "Surprise Box",
        "category": "mobile",
        "price": 500,
        "previousPrice": 600,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Surprise Box (GFT-013)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "113",
        "name": "Crystal Lamp",
        "category": "mobile",
        "price": 1400,
        "previousPrice": 1680,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Crystal Lamp (GFT-014)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "114",
        "name": "Perfume Gift Set",
        "category": "mobile",
        "price": 1200,
        "previousPrice": 1440,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Perfume Gift Set (GFT-015)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "115",
        "name": "Mini Rechargeable Fan",
        "category": "electronics",
        "price": 325,
        "previousPrice": 390,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Mini Rechargeable Fan (SEG-001)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "116",
        "name": "Neck Fan",
        "category": "electronics",
        "price": 450,
        "previousPrice": 540,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Neck Fan (SEG-002)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "117",
        "name": "Foldable Desk Fan",
        "category": "electronics",
        "price": 575,
        "previousPrice": 690,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Foldable Desk Fan (SEG-003)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "118",
        "name": "Power Bank 10,000mAh",
        "category": "electronics",
        "price": 1000,
        "previousPrice": 1200,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Power Bank 10,000mAh (SEG-004)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "119",
        "name": "Power Bank 20,000mAh",
        "category": "electronics",
        "price": 1550,
        "previousPrice": 1860,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Power Bank 20,000mAh (SEG-005)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "120",
        "name": "Fast Charger 20W",
        "category": "electronics",
        "price": 400,
        "previousPrice": 480,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Fast Charger 20W (SEG-006)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "121",
        "name": "Charging Dock",
        "category": "electronics",
        "price": 475,
        "previousPrice": 570,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Charging Dock (SEG-007)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "122",
        "name": "Wireless Charger",
        "category": "electronics",
        "price": 650,
        "previousPrice": 780,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Wireless Charger (SEG-008)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "123",
        "name": "Bluetooth Speaker (Mini)",
        "category": "electronics",
        "price": 700,
        "previousPrice": 840,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Bluetooth Speaker (Mini) (SEG-009)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "124",
        "name": "Bluetooth Earbuds",
        "category": "electronics",
        "price": 525,
        "previousPrice": 630,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Bluetooth Earbuds (SEG-010)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "125",
        "name": "Neckband Earphones",
        "category": "electronics",
        "price": 450,
        "previousPrice": 540,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Neckband Earphones (SEG-011)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "126",
        "name": "RGB Night Light",
        "category": "electronics",
        "price": 325,
        "previousPrice": 390,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality RGB Night Light (SEG-012)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "127",
        "name": "Motion Sensor Light",
        "category": "electronics",
        "price": 450,
        "previousPrice": 540,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Motion Sensor Light (SEG-013)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "128",
        "name": "Rechargeable Emergency Light",
        "category": "electronics",
        "price": 550,
        "previousPrice": 660,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Rechargeable Emergency Light (SEG-014)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "129",
        "name": "USB LED Light",
        "category": "electronics",
        "price": 200,
        "previousPrice": 240,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality USB LED Light (SEG-015)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "130",
        "name": "Electric Lighter (USB Arc)",
        "category": "electronics",
        "price": 325,
        "previousPrice": 390,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Electric Lighter (USB Arc) (SEG-016)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "131",
        "name": "Digital Alarm Clock",
        "category": "electronics",
        "price": 450,
        "previousPrice": 540,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Digital Alarm Clock (SEG-017)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "132",
        "name": "Digital Thermometer",
        "category": "electronics",
        "price": 400,
        "previousPrice": 480,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Digital Thermometer (SEG-018)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "133",
        "name": "Mini Vacuum Cleaner (Desk)",
        "category": "electronics",
        "price": 650,
        "previousPrice": 780,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Mini Vacuum Cleaner (Desk) (SEG-019)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "134",
        "name": "Air Blower (Mini)",
        "category": "electronics",
        "price": 525,
        "previousPrice": 630,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Air Blower (Mini) (SEG-020)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "135",
        "name": "Mini Humidifier",
        "category": "electronics",
        "price": 575,
        "previousPrice": 690,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Mini Humidifier (SEG-021)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "136",
        "name": "Aroma Diffuser",
        "category": "electronics",
        "price": 650,
        "previousPrice": 780,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Aroma Diffuser (SEG-022)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    },
    {
        "id": "137",
        "name": "Mini Air Cooler",
        "category": "electronics",
        "price": 1600,
        "previousPrice": 1920,
        "returnRate": 15,
        "duration": 30,
        "stock": 100,
        "minUnits": 1,
        "description": "High quality Mini Air Cooler (SEG-023)",
        "image": "fa-box",
        "active": true,
        "colors": [
            "Default"
        ],
        "hasOffer": true,
        "offerText": "Special Offer",
        "offerColor": "#ef4444",
        "createdAt": new Date().toISOString()
    }
];
